#	$NetBSD$

ZFSDIR=		${S}/../external/cddl/openzfs
ZFSOSNET=	${S}/../external/cddl/osnet

.PATH:	${ZFSDIR}/module/zcommon
.PATH:	${ZFSDIR}/module/zfs
.PATH:	${ZFSDIR}/module/os/netbsd/spl
.PATH:	${ZFSDIR}/module/os/netbsd/zfs

# OS interfaces are being brought up separately from the common sources.
SRCS+=	abd_os.c zio_crypt.c

# Common OpenZFS sources.
SRCS+=	cityhash.c zfeature_common.c zfs_comutil.c zfs_deleg.c
SRCS+=	zfs_fletcher.c zfs_fletcher_superscalar.c
SRCS+=	zfs_fletcher_superscalar4.c zfs_fletcher_sse.c
SRCS+=	zfs_fletcher_avx512.c zfs_fletcher_intel.c
SRCS+=	zfs_namecheck.c zfs_prop.c zfs_valstr.c zpool_prop.c zprop_common.c

SRCS+=	abd.c aggsum.c arc.c blake3_zfs.c blkptr.c bplist.c bpobj.c
SRCS+=	bptree.c bqueue.c brt.c btree.c dataset_kstats.c dbuf.c dbuf_stats.c
SRCS+=	ddt.c ddt_log.c ddt_stats.c ddt_zap.c dmu.c dmu_direct.c dmu_diff.c
SRCS+=	dmu_object.c dmu_objset.c dmu_recv.c dmu_redact.c dmu_send.c
SRCS+=	dmu_traverse.c dmu_tx.c dmu_zfetch.c dnode.c dnode_sync.c
SRCS+=	dsl_bookmark.c dsl_crypt.c dsl_dataset.c dsl_deadlist.c dsl_deleg.c
SRCS+=	dsl_destroy.c dsl_dir.c dsl_pool.c dsl_prop.c dsl_scan.c
SRCS+=	dsl_synctask.c dsl_userhold.c edonr_zfs.c fm.c gzip.c lz4.c lz4_zfs.c
SRCS+=	lzjb.c metaslab.c mmp.c multilist.c objlist.c pathname.c range_tree.c
SRCS+=	refcount.c rrwlock.c sa.c sha2_zfs.c skein_zfs.c spa.c
SRCS+=	spa_checkpoint.c spa_config.c spa_errlog.c spa_history.c
SRCS+=	spa_log_spacemap.c spa_misc.c spa_stats.c space_map.c space_reftree.c
SRCS+=	txg.c uberblock.c unique.c vdev.c vdev_draid.c vdev_draid_rand.c
SRCS+=	vdev_file.c vdev_indirect.c vdev_indirect_births.c
SRCS+=	vdev_indirect_mapping.c vdev_initialize.c vdev_label.c vdev_mirror.c
SRCS+=	vdev_missing.c vdev_queue.c vdev_raidz.c vdev_raidz_math.c
SRCS+=	vdev_raidz_math_scalar.c vdev_raidz_math_sse2.c vdev_raidz_math_ssse3.c
SRCS+=	vdev_raidz_math_avx2.c vdev_raidz_math_avx512f.c
SRCS+=	vdev_raidz_math_avx512bw.c vdev_rebuild.c vdev_removal.c vdev_root.c
SRCS+=	vdev_trim.c zap.c zap_leaf.c zap_micro.c
SRCS+=	zcp.c zcp_get.c zcp_global.c zcp_iter.c zcp_set.c zcp_synctask.c
SRCS+=	zfeature.c zfs_byteswap.c zfs_chksum.c zfs_fm.c zfs_fuid.c
SRCS+=	zfs_impl.c zfs_ioctl.c zfs_log.c zfs_onexit.c zfs_quota.c
SRCS+=	zfs_ratelimit.c zfs_replay.c zfs_rlock.c zfs_sa.c zfs_vnops.c
SRCS+=	zfs_znode.c zil.c zio.c zio_checksum.c zio_compress.c zio_inject.c
SRCS+=	zle.c zrlock.c zthr.c zvol.c

WARNS=		0
CWARNFLAGS+=	-Wall -Wno-unknown-pragmas -Wno-missing-braces
CWARNFLAGS+=	-Wno-parentheses -Wno-unused -Wno-switch
CWARNFLAGS+=	-Wno-strict-prototypes -Wno-missing-prototypes
CWARNFLAGS+=	${CC_WNO_MAYBE_UNINITIALIZED}

CPPFLAGS+=	-D__KERNEL__ -D_PROPLIB_ZFS_CONFLICT
CPPFLAGS+=	-include ${ZFSDIR}/include/os/netbsd/spl/sys/ccompile.h
CPPFLAGS+=	-I${ZFSDIR}/include/os/netbsd/spl
CPPFLAGS+=	-I${ZFSDIR}/include/os/netbsd/zfs
CPPFLAGS+=	-I${ZFSDIR}/include
CPPFLAGS+=	-I${ZFSDIR}/module/icp/include

# Temporary fallback for interfaces supplied by the existing solaris module.
# OpenZFS headers must precede these so we never use old ZFS core definitions.
CPPFLAGS+=	-I${ZFSOSNET}/sys
CPPFLAGS+=	-I${ZFSOSNET}/dist/common
CPPFLAGS+=	-I${ZFSOSNET}/dist/common/acl
CPPFLAGS+=	-I${ZFSOSNET}/dist/uts/common
CPPFLAGS+=	-I${ZFSOSNET}/dist/uts/common/zmod
