#	$NetBSD: Makefile.rumpkerncomp,v 1.14 2021/09/30 02:00:20 yamaguchi Exp $
#

.include <bsd.own.mk>

RUMPKERNCOMPS=	crypto nv sysproxy tty z simplehook_tester
RUMPSYSEMUS=	sys_cygwin sys_linux sys_sunos

.if make(rumpdescribe)
RUMPKERNCOMPS+=	${RUMPSYSEMUS}
.endif

.if ${MKSLJIT} != "no" || make(rumpdescribe)
RUMPKERNCOMPS+=	sljit
.endif

# The Solaris component is deferred along with ZFS rump support.

.for var in ${RUMPKERNCOMPS}
RUMPKERNLIBS+=lib${var}
RUMPKERNLDADD+=-lrumpkern_${var}
.endfor
