#	$NetBSD: Makefile,v 1.6 2024/06/05 16:37:44 riastradh Exp $

SUBDIR=
SUBDIR+=	ramdisk
SUBDIR+=	ramdisk-cgdroot
# ramdisk-zfsroot is deferred until OpenZFS has crunch and mount_zfs support.

TARGETS+=	release

.include <bsd.subdir.mk>
