.\"	$NetBSD$
.\"
.\" Copyright (c) 2026 Mike Jones <mike@mjones.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd August 17, 2026
.Dt VCCONFIG 8
.Os
.Sh NAME
.Nm vcconfig
.Nd configure a cgd device from a VeraCrypt volume
.Sh SYNOPSIS
.Nm
.Op Fl p Ar pim
.Ar cgd
.Ar device
.Sh DESCRIPTION
The
.Nm
utility reads a VeraCrypt header from the disk partition
.Ar device ,
prompts for a passphrase, and configures the
.Xr cgd 4
device
.Ar cgd
as an AES-XTS mapping of the encrypted data area.
No cgd metadata is stored on the backing partition.
The backing device must use 512-byte logical sectors.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl p Ar pim
Use the VeraCrypt Personal Iterations Multiplier
.Ar pim .
The default value of zero selects 500,000 PBKDF2 iterations.
.El
.Pp
Only normal VeraCrypt volumes using AES-XTS with two 256-bit keys and
PBKDF2-HMAC-SHA512 are supported.
The primary header is used when possible, with automatic fallback to the
backup header.
Hidden volumes, system encryption, in-place encryption, key files, and
other ciphers or key derivation functions are not supported.
.Pp
Mappings can be removed with
.Xr cgdconfig 8 ,
for example:
.Bd -literal -offset indent
cgdconfig -u cgd0
.Ed
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Configure
.Pa cgd0
from a VeraCrypt volume in
.Pa /dev/dk0 :
.Bd -literal -offset indent
vcconfig cgd0 /dev/dk0
.Ed
.Sh SEE ALSO
.Xr cgd 4 ,
.Xr cgdconfig 8
