.\"	$NetBSD$
.\"
.\" Copyright (c) 2026 Mike Jones <mike@mjones.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd August 17, 2026
.Dt VCCONFIG 8
.Os
.Sh NAME
.Nm vcconfig
.Nd configure a VeraCrypt or raw AES-XTS cgd device
.Sh SYNOPSIS
.Nm
.Op Fl p Ar pim
.Ar cgd
.Ar device
.Nm
.Fl k Ar keyfile
.Fl o Ar sectors
.Ar cgd
.Ar device
.Sh DESCRIPTION
By default, the
.Nm
utility reads a VeraCrypt header from the disk partition
.Ar device ,
prompts for a passphrase, and configures the
.Xr cgd 4
device
.Ar cgd
as an AES-XTS mapping of the encrypted data area.
No cgd metadata is stored on the backing partition.
The backing device must use 512-byte logical sectors.
.Pp
Alternatively,
.Fl k
and
.Fl o
configure a raw AES-XTS mapping compatible with the dm-crypt
.Sq aes-xts-plain64
mode.
The raw binary key file must contain exactly 32 or 64 bytes.
The first half is the AES data key and the second half is the AES tweak key.
The offset is specified in 512-byte sectors and applies both to the start of
the encrypted data on the backing device and to the XTS IV sector number.
The mapping extends from the offset to the end of the backing device.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl k Ar keyfile
Read a raw AES-XTS master key from
.Ar keyfile .
This option must be used with
.Fl o
and cannot be used with
.Fl p .
.It Fl o Ar sectors
Start the raw mapping at
.Ar sectors
512-byte sectors into the backing device, and use the same value as the
initial XTS IV sector number.
This option must be used with
.Fl k .
.It Fl p Ar pim
Use the VeraCrypt Personal Iterations Multiplier
.Ar pim .
The default value of zero selects 500,000 PBKDF2 iterations.
.El
.Pp
Only normal VeraCrypt volumes using AES-XTS with two 256-bit keys and
PBKDF2-HMAC-SHA512 are supported.
The primary header is used when possible, with automatic fallback to the
backup header.
Hidden volumes, system encryption, in-place encryption, key files, and
other ciphers or key derivation functions are not supported.
.Pp
Mappings can be removed with
.Xr cgdconfig 8 ,
for example:
.Bd -literal -offset indent
cgdconfig -u cgd0
.Ed
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Configure
.Pa cgd0
from a VeraCrypt volume in
.Pa /dev/dk0 :
.Bd -literal -offset indent
vcconfig cgd0 /dev/dk0
.Ed
.Pp
Configure a raw AES-XTS mapping of
.Pa /dev/nvme0n1p3
using a 64-byte master key and an offset of 256 sectors for both data and IV:
.Bd -literal -offset indent
vcconfig -k master.key -o 256 cgd0 /dev/nvme0n1p3
.Ed
This corresponds to the relevant dm-crypt table fields:
.Bd -literal -offset indent
crypt aes-xts-plain64 <key> 256 <device> 256
.Ed
.Sh SEE ALSO
.Xr cgd 4 ,
.Xr cgdconfig 8
