#	$NetBSD: Makefile,v 1.5 2019/11/11 22:45:32 joerg Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}llvm-tblgen-min
HOSTPROG_CXX=	${_TOOL_PREFIX}llvm-tblgen-min
HOST_SRCDIR=	external/apache2/llvm/bin/tblgen-min

.include "${.CURDIR}/../Makefile.host"
